### ISSUE TITLE
Copy of Resource Groups with more than 200 resources

### ISSUE THREAD

**Issue by alishavez7** [Azure/RGCOPY#2]
Hi Martin,

I am trying to clone a SAP VM but seems there is some limitation on the number of resources in the source RG, getting the below error. Do we need to change something in the script.

Export template is not supported for resource groups that have more than '200' resources.
StatusCode: 409
ReasonPhrase: Conflict
OperationID : 3621d971-5f6d-4f83-8cf6-150bdc3d5f70
 
============================================================
Could not create JSON template from source RG
Export-AzResourceGroup failed
============================================================
 
RGCOPY TERMINATED: 2022-05-26 22:55:45 UTC+5
CALL STACK:     1  <ScriptBlock>
            13235  rgcopy01.ps1
            12218  step-armTemplate
             9003  new-templateSource
              763  test-azResult
 
ERROR MESSAGE: Could not create JSON template from source RG

**Comment by martin-merdes** [comment]
I have updated the documentation regarding this
