### ISSUE TITLE
RGCOPY support for storage accounts and images

### ISSUE THREAD

**Issue by GibbyLi** [Azure/RGCOPY#3]
Hi Martin, 

I have a test RG for OpenShift Cluster  , and I want to copy it to another RG, but RGCOPY always failed. 
I had tried to use RGCOPY to copy a RG with some windows VMs to new RG, and it can successfully copied VNET、NIC、VM、Disk etc, it skipped objects which RGCOPY didn't support. 

Does RGCOPY support to copy OpenShift resource? Do I need to edit some value o rgcopy.ps1 first?

RGCOPY showed these error message ：

12:07:11 PM - Error: Code=InvalidTemplate; Message=Deployment template validation failed: 'The resource 'Microsoft.Compute/images/test-lab-rhel' is not defined in the template. Please see https://aka.ms/arm-template for usage details.'.
 The deployment validation failed
 

============================================================
Deployment 'test-lab-rg.2022-06-23__12-06-32' failed
Check the Azure Activity Log in resource group clone-test-lab
============================================================
 
RGCOPY TERMINATED: 2022-06-23 12:07:11 UTC+0
CALL STACK:     1  <ScriptBlock>
            13242  rgcopy.ps1
            12438  step-deployment
            10072  deploy-templateTarget
 
ERROR MESSAGE: Deployment 'test-lab-rg.2022-06-23__12-06-32' failed

**Comment by martin-merdes** [comment]
Hi GibbyLi,

I have no experience with OpenShift. The supported Azure resource types for RGCOPY are documented here:
https://github.com/Azure/RGCOPY/blob/main/rgcopy-docu.md#supported-azure-resources
Adding new resource types is quite complicated because you have to test and code all dependencies with other resource types

If you attach the RGCOPY ZIP file to this conversation, then I can have a closer look on this.

Regards
Martin

**Comment by GibbyLi** [comment]
Hi Martin，
Thank you for the prompt reply.
If possible can I modify some value to let RGCOPY skip unsupported resouce type (like images, storageAccounts...)?
just let RGCOPY copies continuously the resources which are supported.

**Comment by martin-merdes** [comment]
RGCOPY simply deploys Azure resources using an ARM template. However, images and storage accounts contain data that cannot be included in the ARM template. Therefore, there is no easy way for extending RGCOPY for these resource types.
RGCOPY can only copy data of disks and NetApp volumes. Copying NetApp volumes by RGCOPY was a project that took me more than a month to develop.

**Comment by martin-merdes** [comment]
There is another reason why you cannot simply copy an Azure Storage Account. The name of a storage account must be unique in Azure. You cannot re-use the same name in a different resource group.
