### ISSUE TITLE
Stop copying if ASGs are used in network rules

### ISSUE THREAD

**Issue by kselas** [Azure/RGCOPY#5]
Hi, Martin!

I have encountered an interesting bug in COPY mode. When running with standard parameters, the following error appears, referring to NSG and ASG (specified as destinations in NSG). This happens at the deployment step, after which the script stops.

In source RG several network rules specify Application security group as Destination.

```
{"code": "InvalidTemplateDeployment", "message": "The template deployment 'rgcopy.vm_template_rg.TARGET' is not valid according to the validation procedure. The tracking id is ''. See inner errors for details."}

Inner Errors: 
{"code": "SecurityRuleParametersMissing", "target": "/subscriptions//resourceGroups/vm_template_rg/providers/Microsoft.Network/networkSecurityGroups/saturn-nsg", "message": "Required security rule parameters are missing for security rule with Id: /subscriptions//resourceGroups/vm_template_rg/providers/Microsoft.Network/networkSecurityGroups/saturn-nsg/securityRules/SSH. Security rule must specify DestinationAddressPrefixes, DestinationAddressPrefix, or DestinationApplicationSecurityGroups."}
```

**Comment by martin-merdes** [comment]
Hi,

the resource type "Microsoft.Network/applicationSecurityGroups" is currently not supported in RGCOPY. The supported resources are listed here: https://github.com/Azure/RGCOPY/blob/main/rgcopy-docu.md#supported-azure-resources

Please send me the RGCOPY zip file (containing all logs and templates). I will check whether I can add support for this scenario in the next version of RGCOPY.

In the meanwhile, you could use the following RGCOPY parameter to skip copying all security rules.

skipSecurityRules = '*' 

Thanks
Martin
